name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write  # Needed to push changes

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: output  # Checkout the output branch

      - name: Generate Snake Animation with Black Color
        uses: Platane/snk@v3
        with:
          github_user_name: hi-mehedi
          outputs: github-snake.svg
          color_snake: "#FFFFFF"  # Black snake
          color_dots: "#000000"   # White dots for contrast

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-snake.svg
          git commit -m "Updated snake animation color to black" || echo "No changes to commit"
          git push origin output  # Push to the output branch
